version: '3.8'

services:
  app_python:
    image: lok52/app_python:latest
    ports:
      - 80:8000
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"
