version: '3.8'

services:
  app_python:
    image: lok52/app_python
    build: app_python
    ports:
      - 8000:8000
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"
  app_rust:
    image: lok52/app_rust
    build: app_rust
    ports:
      - 8001:8000
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"
