- name: Create project dir
  become: true
  file:
    dest: /opt/devops
    state: directory
    mode: 0755
    recurse: true

- name: Copy Docker Compose file
  become: true
  copy:
    src: "{{ docker_compose_path }}"
    dest: /opt/devops/docker-compose.yml
    mode: 0755

- name: Deploy Docker Compose stack
  community.docker.docker_compose:
    project_src: /opt/devops
    restarted: true
