apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-rust
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-rust
  template:
    metadata:
      labels:
        app: app-rust
    spec:
      containers:
      - name: app-rust
        image: lok52/app_rust:latest
        ports:
        - containerPort: 8000
