apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  labels:
    {{- include "app-python.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.username | b64enc | quote }}
  password: {{ .Values.password | b64enc | quote }}