version: "3.8"
services:
  loki:
    image: grafana/loki:2.3.0
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - /var/log:/var/log
      - ${CONTAINERS_PATH}:/var/lib/docker/containers:ro
      - ./promtail.yml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - loki

  prometheus:
     image: prom/prometheus:v2.29.2
     volumes:
       - prometheus:/prometheus
       - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
     networks:
       - loki
     ports:
       - 9090:9090

networks:
  loki:

volumes:
  grafana:
  prometheus:
